[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
backend = { path = "../backend" }
clap = { version = "4.5.16", features = ["derive"] }
actix-web = { version = "4.9.0", features = ["rustls-0_23"] }
tokio = { version = "1.39.3", features = ["full"] }
